#!/bin/sh
set -e

# Time intervals for reporting: Monday to Friday, 9 AM to 8 PM.
date +%u%t%k | grep -v '^[67]' | grep -qE '(0[7-9]|1.)$' || exit

if [ "$1" = 'ip' ]; then
    ip="$(GET -t30 http://checkip.dyndns.com:8245/ | sed -e 's/^.*: //' -e 's/<.*$//')" || exit 1
    [ -z "$ip" ] && exit 2
    msg="$ip online"
fi

echo "${msg:-offline}" | sendxmpp --ssl -f /etc/sendxmpp.conf \
    "$(echo 'dmFsZXJ5LnZ2QGdtYWlsLmNvbQo=' | base64 -d)"
